### PR TITLE
[ENH] Load data: Add data loader for H5AD format

### PR DESCRIPTION
**Pull request by pavlin-policar**
##### Issue
The load data widget does not support the `h5ad` format. This format is by far the nicest and fastest format I've used for sparse gene expression matrices. `scanpy` and `seurat` both support this format.

##### Description of changes
Add an H5AD reader.

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by JakaKokosar** [comment]
Hm.. anndata is not available trough conda-forge channel (it is on bioconda channel). This means we will brake recipe build for the next release. 

Support for multiple channels in recipes is not supported: https://github.com/conda/conda-build/pull/3656

**Comment by pavlin-policar** [comment]
Is it possible to specify additional conda channels when building the package? `anndata` is available on conda through `bioconda` (taken from their readme: `conda install anndata -c bioconda`). I don't actually think this is possible, unforuntately.

It seems to me that this is constantly popping up. Isn't there some way to manually install the package through pip using [`build.sh`](https://docs.conda.io/projects/conda-build/en/latest/resources/build-scripts.html)?

**Comment by JakaKokosar** [comment]
https://github.com/conda-forge/staged-recipes/pull/9398

I have added you to be a maintainer, please confirm in PR.

**Comment by JakaKokosar** [comment]
This looks good to me! Also, the recipe tests pass and will hopefully be merged soon.

@VesnaT Can you maybe quickly look at it and merge if OK?

**Comment by pavlin-policar** [comment]
Actually, since we’re on the topic of licenses could we make sure that
anndata is properly licensed so we can include it into our orange without
making things complicated?  Does anyone know who we could talk to about
this?

**Comment by JakaKokosar** [comment]
What is wrong with the current license?

**Comment by pavlin-policar** [comment]
Never mind, I checked the license and it's got the BSD-3 clause, which should be fine.

A year or so ago there was a discussion in the lab about licensing and we had to be careful about which packages were added to dependencies because of this. I don't really know if that lead anywhere, but it's better to check this before adding a potentially non-commercially licensed software package to dependencies. But like I said, this one has BSD-3, which should be fine.

**Pull request merged**
